version: "3"

services:
  pocketbase-vue-starter:
    image: ghcr.io/mrsessions/pocketbase-vue-starter:latest
    build:
      context: ./
    container_name: pocketbase-vue-starter
    environment:
      - POCKETBASE_DISABLE_UI=false # Set to true to disable the PocketBase UI
      - POCKETBASE_ADMIN_EMAIL=admin@example.com #This is the default if you don't set it or this value is removed
      - POCKETBASE_ADMIN_PASSWORD=1234567890 #This is the default if you don't set it or this value is removed
    ports:
      - 8090:80
    volumes:
      - pocketbase-db:/app/pb_data
    restart: unless-stopped

volumes:
  pocketbase-db: